// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWf95PKG4ME-jR6UKimMljwuiHjckf3MI',
    appId: '1:341423424291:web:64e6489c60dfeddca78296',
    messagingSenderId: '341423424291',
    projectId: 'flutterfire-ui-codelab-97e2a',
    authDomain: 'flutterfire-ui-codelab-97e2a.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-97e2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApZ6PlZ8FooVVkgFHj4XO_lFx1pJTakQ0',
    appId: '1:341423424291:android:38bf11720456c3daa78296',
    messagingSenderId: '341423424291',
    projectId: 'flutterfire-ui-codelab-97e2a',
    storageBucket: 'flutterfire-ui-codelab-97e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsBuO6N5VSavBgAqODveFcxU42hS-EEbE',
    appId: '1:341423424291:ios:a2a19b813b525772a78296',
    messagingSenderId: '341423424291',
    projectId: 'flutterfire-ui-codelab-97e2a',
    storageBucket: 'flutterfire-ui-codelab-97e2a.appspot.com',
    iosClientId: '341423424291-gkf0fugesp55nksdoopffble4ttjijqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsBuO6N5VSavBgAqODveFcxU42hS-EEbE',
    appId: '1:341423424291:ios:a2a19b813b525772a78296',
    messagingSenderId: '341423424291',
    projectId: 'flutterfire-ui-codelab-97e2a',
    storageBucket: 'flutterfire-ui-codelab-97e2a.appspot.com',
    iosClientId: '341423424291-gkf0fugesp55nksdoopffble4ttjijqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
